from lymph.schema.schema import Schema


def build(schema, name):
    """Build a service stub.

    :param schema: Service schema generated by ``lymph schema-gen``.
    :param name: Name of service to stub, accept also ``name@version`` form.

    :return: An object that emulate the service contract.

    :raises ValueError: In case given service name or version doesn't exist.

    """
    schema = Schema(schema)
    return schema.build_service(name)

